//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.17379
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sp_Ctx.Sharepoint {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/OfficeServer/QueryService", ConfigurationName="Sharepoint.QueryServiceSoap")]
    public interface QueryServiceSoap {
        
        // CODEGEN : La génération du contrat de message depuis l'espace de noms de wrapper (urn:Microsoft.Search) du message QueryRequest ne correspond pas à la valeur par défaut (http://microsoft.com/webservices/OfficeServer/QueryService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Microsoft.Search/Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sp_Ctx.Sharepoint.QueryResponse Query(Sp_Ctx.Sharepoint.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/OfficeServer/QueryService/QueryEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QueryEx(string queryXml);
        
        // CODEGEN : La génération du contrat de message depuis l'espace de noms de wrapper (urn:Microsoft.Search) du message RegistrationRequest ne correspond pas à la valeur par défaut (http://microsoft.com/webservices/OfficeServer/QueryService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Microsoft.Search/Registration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sp_Ctx.Sharepoint.RegistrationResponse Registration(Sp_Ctx.Sharepoint.RegistrationRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l'espace de noms de wrapper (urn:Microsoft.Search) du message StatusRequest ne correspond pas à la valeur par défaut (http://microsoft.com/webservices/OfficeServer/QueryService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Microsoft.Search/Status", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sp_Ctx.Sharepoint.StatusResponse Status(Sp_Ctx.Sharepoint.StatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/OfficeServer/QueryService/GetPortalSearchInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPortalSearchInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/OfficeServer/QueryService/GetSearchMetadata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSearchMetadata();
        
        // CODEGEN : La génération du contrat de message depuis l'espace de noms de wrapper (urn:Microsoft.Search) du message RecordClickRequest ne correspond pas à la valeur par défaut (http://microsoft.com/webservices/OfficeServer/QueryService)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Microsoft.Search/RecordClick", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sp_Ctx.Sharepoint.RecordClickResponse RecordClick(Sp_Ctx.Sharepoint.RecordClickRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/OfficeServer/QueryService/GetQuerySuggestions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetQuerySuggestions(string queryXml);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Query", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class QueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microsoft.Search", Order=0)]
        public string queryXml;
        
        public QueryRequest() {
        }
        
        public QueryRequest(string queryXml) {
            this.queryXml = queryXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryResponse", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class QueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microsoft.Search", Order=0)]
        public string QueryResult;
        
        public QueryResponse() {
        }
        
        public QueryResponse(string QueryResult) {
            this.QueryResult = QueryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Registration", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class RegistrationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microsoft.Search", Order=0)]
        public string registrationXml;
        
        public RegistrationRequest() {
        }
        
        public RegistrationRequest(string registrationXml) {
            this.registrationXml = registrationXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrationResponse", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class RegistrationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microsoft.Search", Order=0)]
        public string RegistrationResult;
        
        public RegistrationResponse() {
        }
        
        public RegistrationResponse(string RegistrationResult) {
            this.RegistrationResult = RegistrationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Status", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class StatusRequest {
        
        public StatusRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatusResponse", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class StatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microsoft.Search", Order=0)]
        public string StatusResult;
        
        public StatusResponse() {
        }
        
        public StatusResponse(string StatusResult) {
            this.StatusResult = StatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecordClick", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class RecordClickRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microsoft.Search", Order=0)]
        public string clickInfoXml;
        
        public RecordClickRequest() {
        }
        
        public RecordClickRequest(string clickInfoXml) {
            this.clickInfoXml = clickInfoXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecordClickResponse", WrapperNamespace="urn:Microsoft.Search", IsWrapped=true)]
    public partial class RecordClickResponse {
        
        public RecordClickResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryServiceSoapChannel : Sp_Ctx.Sharepoint.QueryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryServiceSoapClient : System.ServiceModel.ClientBase<Sp_Ctx.Sharepoint.QueryServiceSoap>, Sp_Ctx.Sharepoint.QueryServiceSoap {
        
        public QueryServiceSoapClient() {
        }
        
        public QueryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sp_Ctx.Sharepoint.QueryResponse Sp_Ctx.Sharepoint.QueryServiceSoap.Query(Sp_Ctx.Sharepoint.QueryRequest request) {
            return base.Channel.Query(request);
        }
        
        public string Query(string queryXml) {
            Sp_Ctx.Sharepoint.QueryRequest inValue = new Sp_Ctx.Sharepoint.QueryRequest();
            inValue.queryXml = queryXml;
            Sp_Ctx.Sharepoint.QueryResponse retVal = ((Sp_Ctx.Sharepoint.QueryServiceSoap)(this)).Query(inValue);
            return retVal.QueryResult;
        }
        
        public System.Data.DataSet QueryEx(string queryXml) {
            return base.Channel.QueryEx(queryXml);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sp_Ctx.Sharepoint.RegistrationResponse Sp_Ctx.Sharepoint.QueryServiceSoap.Registration(Sp_Ctx.Sharepoint.RegistrationRequest request) {
            return base.Channel.Registration(request);
        }
        
        public string Registration(string registrationXml) {
            Sp_Ctx.Sharepoint.RegistrationRequest inValue = new Sp_Ctx.Sharepoint.RegistrationRequest();
            inValue.registrationXml = registrationXml;
            Sp_Ctx.Sharepoint.RegistrationResponse retVal = ((Sp_Ctx.Sharepoint.QueryServiceSoap)(this)).Registration(inValue);
            return retVal.RegistrationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sp_Ctx.Sharepoint.StatusResponse Sp_Ctx.Sharepoint.QueryServiceSoap.Status(Sp_Ctx.Sharepoint.StatusRequest request) {
            return base.Channel.Status(request);
        }
        
        public string Status() {
            Sp_Ctx.Sharepoint.StatusRequest inValue = new Sp_Ctx.Sharepoint.StatusRequest();
            Sp_Ctx.Sharepoint.StatusResponse retVal = ((Sp_Ctx.Sharepoint.QueryServiceSoap)(this)).Status(inValue);
            return retVal.StatusResult;
        }
        
        public string GetPortalSearchInfo() {
            return base.Channel.GetPortalSearchInfo();
        }
        
        public System.Data.DataSet GetSearchMetadata() {
            return base.Channel.GetSearchMetadata();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sp_Ctx.Sharepoint.RecordClickResponse Sp_Ctx.Sharepoint.QueryServiceSoap.RecordClick(Sp_Ctx.Sharepoint.RecordClickRequest request) {
            return base.Channel.RecordClick(request);
        }
        
        public void RecordClick(string clickInfoXml) {
            Sp_Ctx.Sharepoint.RecordClickRequest inValue = new Sp_Ctx.Sharepoint.RecordClickRequest();
            inValue.clickInfoXml = clickInfoXml;
            Sp_Ctx.Sharepoint.RecordClickResponse retVal = ((Sp_Ctx.Sharepoint.QueryServiceSoap)(this)).RecordClick(inValue);
        }
        
        public string[] GetQuerySuggestions(string queryXml) {
            return base.Channel.GetQuerySuggestions(queryXml);
        }
    }
}
